services:
  # A static site
  - type: web
    name: Secret Network Website Dev
    env: static
    buildCommand: yarn build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true # optional
    routes:
      - type: redirect
        source: /agents
        destination: https://scrt.network/get-involved/become-secret-agent